# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_CLASS/Class4/prj/class4.srcs/sources_1/ip/AXI_LITE/AXI_LITE.xci
# IP: The module: 'AXI_LITE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_CLASS/Class4/prj/class4.gen/sources_1/ip/AXI_LITE/AXI_LITE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_LITE'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/FPGA_CLASS/Class4/prj/class4.srcs/sources_1/ip/AXI_LITE/AXI_LITE.xci
# IP: The module: 'AXI_LITE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_CLASS/Class4/prj/class4.gen/sources_1/ip/AXI_LITE/AXI_LITE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_LITE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
