# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/FPGA_COURSE/Class4/prj/class4.srcs/sources_1/ip/fifo_3/fifo_3.xci
# IP: The module: 'fifo_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/fifo_3/fifo_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/fifo_3/fifo_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/FPGA_COURSE/Class4/prj/class4.srcs/sources_1/ip/fifo_3/fifo_3.xci
# IP: The module: 'fifo_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/fifo_3/fifo_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/fifo_3/fifo_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
