webtalk_init -webtalk_dir E:/FPGA_CLASS/Class4/prj/class4.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Aug 24 15:19:38 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "df729dbf-0b49-4376-b79b-3b26eb48767d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6da8a4eec12447dcbdedd0fb238f80a1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "97" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "623935100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1717268553 -regid "" -xml E:/FPGA_CLASS/Class4/prj/class4.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/FPGA_CLASS/Class4/prj/class4.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/FPGA_CLASS/Class4/prj/class4.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
