# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/FPGA_COURSE/Class4/prj/class4.srcs/sources_1/ip/set_ram/set_ram.xci
# IP: The module: 'set_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/set_ram/set_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'set_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: g:/FPGA_COURSE/Class4/prj/class4.srcs/sources_1/ip/set_ram/set_ram.xci
# IP: The module: 'set_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/set_ram/set_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'set_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
