# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_CLASS/Class5/prj/class5.srcs/sources_1/ip/rom_dout/rom_dout.xci
# IP: The module: 'rom_dout' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_CLASS/Class5/prj/class5.gen/sources_1/ip/rom_dout/rom_dout_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_dout'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/FPGA_CLASS/Class5/prj/class5.srcs/sources_1/ip/rom_dout/rom_dout.xci
# IP: The module: 'rom_dout' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_CLASS/Class5/prj/class5.gen/sources_1/ip/rom_dout/rom_dout_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_dout'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
