# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/FPGA_COURSE/Class4/prj/class4.srcs/sources_1/ip/clk_generate/clk_generate.xci
# IP: The module: 'clk_generate' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/clk_generate/clk_generate_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generate'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/clk_generate/clk_generate.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generate'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/clk_generate/clk_generate_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generate'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/FPGA_COURSE/Class4/prj/class4.srcs/sources_1/ip/clk_generate/clk_generate.xci
# IP: The module: 'clk_generate' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/clk_generate/clk_generate_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generate'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/clk_generate/clk_generate.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generate'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/FPGA_COURSE/Class4/prj/class4.gen/sources_1/ip/clk_generate/clk_generate_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generate'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
