# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_CLASS/Class4/prj/class4.srcs/sources_1/ip/fifo_wrdata/fifo_wrdata.xci
# IP: The module: 'fifo_wrdata' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_CLASS/Class4/prj/class4.gen/sources_1/ip/fifo_wrdata/fifo_wrdata.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrdata'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_CLASS/Class4/prj/class4.gen/sources_1/ip/fifo_wrdata/fifo_wrdata_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrdata'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_CLASS/Class4/prj/class4.gen/sources_1/ip/fifo_wrdata/fifo_wrdata_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrdata'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/FPGA_CLASS/Class4/prj/class4.srcs/sources_1/ip/fifo_wrdata/fifo_wrdata.xci
# IP: The module: 'fifo_wrdata' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_CLASS/Class4/prj/class4.gen/sources_1/ip/fifo_wrdata/fifo_wrdata.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrdata'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_CLASS/Class4/prj/class4.gen/sources_1/ip/fifo_wrdata/fifo_wrdata_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrdata'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_CLASS/Class4/prj/class4.gen/sources_1/ip/fifo_wrdata/fifo_wrdata_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrdata'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
